version: "2.1"
    
services:
  mysql:
    image: mysql:5.7
    logging:
      driver: none
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      inner:
        aliases:
          - mysql
  crud:
    build:
      context: ./
      dockerfile: Dockerfile.development
    volumes:
      - ./:/app
    environment:
      DB_NAME: database
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: mysql
      DB_PORT: 3306
    ports:
      - "8000:8000"
    expose:
      - "8000"
    dns:
      - "8.8.8.8"
    networks:
      inner:
        aliases:
          - crud
    depends_on:
      mysql:
        condition: service_healthy
networks:
  inner:
    driver: bridge

volumes:
  db_data: {}
